import os, sys, shutil
import json
import numpy as np
from numpy import pi as PI
import warnings

from astropy.time import Time
import astropy.units as u
from astropy.io import fits

from synphot import Empirical1D, SpectralElement

response_files_dir = os.path.join(os.path.dirname(__file__), 'response_files')

class UVEX():
    '''
        Container class to load telescope CBE values and bandpasses
        from a configuration generated by uvex_response.
        
        Parameters
        ----------
        caldb : string
            Directory name for a UVEX CALDB version
    '''
    def __init__(self, caldb=None):
    
        # Check for existence of CALDBs
        avail_caldb = np.array([f for f in os.listdir(response_files_dir) 
                                if (os.path.isdir(os.path.join(response_files_dir, f)) and f.startswith('2'))])
        if len(avail_caldb) == 0:
            raise ValueError(f"No available CALDBs in {response_files_dir}. Please install a CALDB using install_uvex_caldb.")
        
        # Define CALDB we are using
        if caldb is None:
            latest = max(Time([c[:4]+'-'+c[4:6]+'-'+c[6:8] for c in avail_caldb])).iso
            latest_option = [latest[:4]+latest[5:7]+latest[8:10] in c for c in avail_caldb]
            if np.sum(latest_option) == 1:
                self.caldb = avail_caldb[latest_option][0]
            else:
                versions = [c[9:] for c in avail_caldb[latest_option]]
                self.caldb = avail_caldb[latest_option][np.argmax(versions)]
                warnings.warn(f"Multiple CALDBs available for {latest}; using {self.caldb}")
        else:
            if caldb not in avail_caldb:
                raise ValueError(f"CALDB version {caldb} not available in response_files.")
            self.caldb = caldb
        config_file = os.path.join(response_files_dir,self.caldb,'config','response_files.json')
        with open(config_file) as f:
            self.config = json.load(f)
        caldb_dir = os.path.join(response_files_dir,self.caldb,'etc','imager')
    
        # Characteristics
        self.EPD = float(self.config['uvex']['EPD']['value']) * u.cm
        self.PIX_UM = float(self.config['uvex']['PIXEL_UM']['value']) * u.micron
        self.PLATE_SCALE = float(self.config['uvex']['PLATE_SCALE']['value']) * u.arcsec / self.PIX_UM
        self.PIXEL = (self.PIX_UM * self.PLATE_SCALE)**2 # Pixel area

        self.READ_NOISE = {
            'nuv': float(self.config['read_noise']['nuv']['value']) * u.electron,
            'fuv': float(self.config['read_noise']['fuv']['value']) * u.electron,
        }
        self.DARK_CURRENT = {
            'nuv': float(self.config['dark_current']['nuv']['value']) * u.electron / u.s,
            'fuv': float(self.config['dark_current']['fuv']['value']) * u.electron / u.s,
        }

        self.NPIX = float(self.config['uvex']['NPIX_IMG']['value'])
        
        # Additional background scaling term not currently in uvex_response
        self.scattered_light_scaling_lya = 0.5
        self.scattered_light_scaling_zodi = 0.5
        self.scattered_light_scaling_galactic = 0.5
        
        # Ly-alpha background level in kR
        self.lya_kr = 2
        
        # Load in filter bandpasses from uvex_response generated config as SpectralElement objects
        with fits.open(os.path.join(caldb_dir, 'nuv_bandpass.fits')) as hdul:
            nuv_data = hdul[1].data
        self.nuv_bandpass = SpectralElement(Empirical1D,
                                            points = nuv_data['WAVELENGTH'], lookup_table = nuv_data['THROUGHPUT'])
        with fits.open(os.path.join(caldb_dir, 'fuv_bandpass.fits')) as hdul:
            fuv_data = hdul[1].data
        self.fuv_bandpass = SpectralElement(Empirical1D,
                                            points = fuv_data['WAVELENGTH'], lookup_table = fuv_data['THROUGHPUT'])
        
        # Cherenkov passes for background contribution
        with fits.open(os.path.join(caldb_dir, 'nuv_cherenkov_bandpass.fits')) as hdul:
            nuv_cherenkov_data = hdul[1].data
        self.nuv_cherenkov_bandpass = SpectralElement(Empirical1D,
                                            points = nuv_cherenkov_data['WAVELENGTH'], lookup_table = nuv_cherenkov_data['THROUGHPUT'])
        with fits.open(os.path.join(caldb_dir, 'fuv_cherenkov_bandpass.fits')) as hdul:
            fuv_cherenkov_data = hdul[1].data
        self.fuv_cherenkov_bandpass = SpectralElement(Empirical1D,
                                            points = fuv_cherenkov_data['WAVELENGTH'], lookup_table = fuv_cherenkov_data['THROUGHPUT'])

    @property
    def AREA(self):
        '''
        Returns telescope area as calculated from Entrance Pupil Diameter
        '''
        return PI * (self.EPD*0.5)**2
    
    def get_caldb(self):
        '''
        Returns the version of the CALDB in use
        '''
        return self.caldb

def install_uvex_etc_caldb():
    '''
    Copies a provided CALDB directory into response_files
    '''
    # Get CALDB directory from command line argument
    if len(sys.argv) < 2:
        print("Usage: install_uvex_etc_caldb [PATH_TO_CALDB_FOLDER]")
        return False
    caldb_dir = sys.argv[1]

    # Check that its contents are as expected
    contents = [os.path.relpath(os.path.join(r, f), caldb_dir) for r, d, files in os.walk(caldb_dir) for f in files]
    required = [os.path.join('config', 'response_files.json'), 
                os.path.join('etc', 'imager', 'nuv_bandpass.fits'), 
                os.path.join('etc', 'imager', 'fuv_bandpass.fits'), 
                os.path.join('etc', 'imager', 'nuv_cherenkov_bandpass.fits'),
                os.path.join('etc', 'imager', 'fuv_cherenkov_bandpass.fits')]
    if not all([r in contents for r in required]):
        raise ValueError(f"Invalid CALDB: {caldb_dir} does not contain the required response files for the UVEX imager ETC.")
        return False
    
    # Copy folder across to response_files
    shutil.copytree(caldb_dir, os.path.join(response_files_dir, os.path.basename(caldb_dir)), dirs_exist_ok=True)
    print(f"Installed CALDB {caldb_dir} in UVEX imager ETC")

def list_installed_caldbs():
    '''
    Lists the CALDBs currently installed in the UVEX imager ETC
    '''
    # Check for existence of CALDBs
    avail_caldb = np.array([f for f in os.listdir(response_files_dir) 
                            if (os.path.isdir(os.path.join(response_files_dir, f)) and f.startswith('2'))])
    if len(avail_caldb) == 0:
        print(f"No available CALDBs in {response_files_dir}. Please install a CALDB using install_uvex_caldb.")
    else:
        print(f"Available CALDBs: \n - {'\n - '.join(avail_caldb)}")