import os
import json
import numpy as np
from numpy import pi as PI
import warnings

from astropy.time import Time
import astropy.units as u

from synphot import Empirical1D, SpectralElement
from synphot.models import ConstFlux1D

from . import backgrounds

response_files_dir = os.path.join(os.path.dirname(__file__), 'response_files')

class UVEX():
    '''
        Container class to load telescope CBE values and bandpasses
        from a configuration generated by uvex_response.
        
        Parameters
        ----------
        caldb : string
            Directory name for a UVEX CALDB version
    '''
    def __init__(self, caldb=None):
    
        # Check for existence of CALDBs
        avail_caldb = np.array([f for f in os.listdir(response_files_dir) if not f.startswith('.')])
        if len(avail_caldb) == 0:
            raise ValueError("No available CALDBs in response_files.")
        
        # Define CALDB we are using
        if caldb is None:
            latest = max(Time([c[:4]+'-'+c[4:6]+'-'+c[6:8] for c in avail_caldb])).iso
            latest_option = [latest[:4]+latest[5:7]+latest[8:10] in c for c in avail_caldb]
            if np.sum(latest_option) == 1:
                self.caldb = avail_caldb[latest_option][0]
            else:
                versions = [c[9:] for c in avail_caldb[latest_option]]
                self.caldb = avail_caldb[latest_option][np.argmax(versions)]
                warnings.warn(f"Multiple CALDBs available for {latest}; using {self.caldb}")
        else:
            if caldb not in avail_caldb:
                raise ValueError(f"CALDB version {caldb} not available in response_files.")
            self.caldb = caldb
        config_file = os.path.join(response_files_dir,self.caldb,'config','response_files.json')
        with open(config_file) as f:
            self.config = json.load(f)
        caldb_dir = os.path.join(response_files_dir,self.caldb,'etc','imager')
    
        # Characteristics
        self.EPD = float(self.config['uvex']['EPD']['value']) * u.cm
        self.PIX_UM = float(self.config['uvex']['PIXEL_UM']['value']) * u.micron
        self.PLATE_SCALE = float(self.config['uvex']['PLATE_SCALE']['value']) * u.arcsec / self.PIX_UM
        self.PIXEL = (self.PIX_UM * self.PLATE_SCALE)**2 # Pixel area

        self.READ_NOISE = {
            'nuv': float(self.config['read_noise']['nuv']['value']) * u.electron,
            'fuv': float(self.config['read_noise']['fuv']['value']) * u.electron,
        }
        self.DARK_CURRENT = {
            'nuv': float(self.config['dark_current']['nuv']['value']) * u.electron / u.s,
            'fuv': float(self.config['dark_current']['fuv']['value']) * u.electron / u.s,
        }

        self.NPIX = float(self.config['uvex']['NPIX_IMG']['value'])
        
        # Additional background scaling term not currently in uvex_response
        self.scattered_light_scaling_lya = 0.5
        self.scattered_light_scaling_zodi = 0.5
        self.scattered_light_scaling_galactic = 0.5
        
        # Ly-alpha background level in kR
        self.lya_kr = 2
        
        # Load in filter bandpasses from uvex_response generated config as SpectralElement objects
        nuv_data = np.genfromtxt(os.path.join(caldb_dir, 'nuv_bandpass.txt'))
        self.nuv_bandpass = SpectralElement(Empirical1D,
                                            points = nuv_data[:,0], lookup_table = nuv_data[:,1])
        fuv_data = np.genfromtxt(os.path.join(caldb_dir, 'fuv_bandpass.txt'))
        self.fuv_bandpass = SpectralElement(Empirical1D,
                                            points = fuv_data[:,0], lookup_table = fuv_data[:,1])
        
        # Cherenkov passes for background contribution
        nuv_cherenkov_data = np.genfromtxt(os.path.join(caldb_dir, 'nuv_cherenkov_bandpass.txt'))
        self.nuv_cherenkov_bandpass = SpectralElement(Empirical1D,
                                            points = nuv_cherenkov_data[:,0], lookup_table = nuv_cherenkov_data[:,1])
        fuv_cherenkov_data = np.genfromtxt(os.path.join(caldb_dir, 'fuv_cherenkov_bandpass.txt'))
        self.fuv_cherenkov_bandpass = SpectralElement(Empirical1D,
                                            points = fuv_cherenkov_data[:,0], lookup_table = fuv_cherenkov_data[:,1])
        
        # Other background-related bandpasses as needed

    @property
    def AREA(self):
        '''
        Returns telescope area as calculated from Entrance Pupil Diameter
        '''
        return PI * (self.EPD*0.5)**2
    
    def get_caldb(self):
        '''
        Returns the version of the CALDB in use
        '''
        return self.caldb
