name: Tests 
on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main

jobs:
  tests:
    name: Run pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Download CALDB
        run: |
          curl -L "https://www.uvex.caltech.edu/system/media_files/binaries/42/original/20260924_v0.1e.zip?1790639225" -o ./uvex_imager_etc/response_files/20260924_v0.1e.zip 
          unzip ./uvex_imager_etc/response_files/20260924_v0.1e.zip -d ./uvex_imager_etc/response_files/20260924_v0.1e

      - name: Run Pytest
        run: pytest
